// AUTO-GENERATED by autoresearch/export_params.py — DO NOT EDIT MANUALLY
// Generated from engine.py PARAMS (Sharpe-optimized)

export const OPTIMIZED_WEIGHTS = {
  momentum: 0.4,
  meanReversion: 0.1,
  quality: 0.15,
  flow: 0.1,
  risk: 0.15,
  crowding: 0.1,
} as const;

export const OPTIMIZED_ZSCORE = {
  mean: 50.0,
  sd: 16.67,
} as const;

export const OPTIMIZED_SIGMOID_STEEPNESS = 1.5;

export const OPTIMIZED_KELLY = {
  fraction: 0.25,
  maxPositionPct: 0.15,
  payoffRatio: 2.0,
} as const;

export const OPTIMIZED_COSTS = {
  transactionCostBps: 10.0,
  slippageBps: 5.0,
} as const;

export const OPTIMIZED_THRESHOLDS = {
  buyProbThreshold: 0.55,
  buyEdgeThreshold: 0.1,
} as const;

export const OPTIMIZED_EMPIRICAL_PROB_MAP: ReadonlyArray<[number, number]> = [
  [1.0, 0.72],
  [0.8, 0.68],
  [0.5, 0.62],
  [0.3, 0.56],
  [0.1, 0.52],
  [0.0, 0.48],
  [-0.3, 0.42],
  [-999, 0.35],
];

