#!/usr/bin/env python3
"""
Export optimized parameters from engine.py to JSON and TypeScript.

Usage:
  python autoresearch/export_params.py

Outputs:
  - autoresearch/optimized-params.json  (machine-readable snapshot)
  - server/autoresearch-params.ts       (typed TypeScript constants)
"""

import json
import sys
import os
from pathlib import Path

# Ensure autoresearch/ is importable
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from engine import PARAMS

SCRIPT_DIR = Path(__file__).parent
REPO_ROOT = SCRIPT_DIR.parent
JSON_OUT = SCRIPT_DIR / "optimized-params.json"
TS_OUT = REPO_ROOT / "server" / "autoresearch-params.ts"


def serialize_params(params: dict) -> dict:
    """Strip non-serializable keys and convert tuples to lists."""
    out = {}
    for k, v in params.items():
        if k == "compute_signals":
            continue  # callable, not serializable
        if isinstance(v, list):
            # Convert list of tuples to list of lists for JSON
            out[k] = [list(item) if isinstance(item, tuple) else item for item in v]
        else:
            out[k] = v
    return out


def snake_to_camel(name: str) -> str:
    """Convert snake_case to camelCase."""
    parts = name.split("_")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def generate_typescript(params: dict) -> str:
    """Generate typed TypeScript constants from params."""
    lines = [
        "// AUTO-GENERATED by autoresearch/export_params.py — DO NOT EDIT MANUALLY",
        f"// Generated from engine.py PARAMS (Sharpe-optimized)",
        "",
    ]

    # Weights
    w = params["weights"]
    lines.append("export const OPTIMIZED_WEIGHTS = {")
    for key, val in w.items():
        ts_key = snake_to_camel(key)
        lines.append(f"  {ts_key}: {val},")
    lines.append("} as const;")
    lines.append("")

    # Z-score params
    lines.append("export const OPTIMIZED_ZSCORE = {")
    lines.append(f"  mean: {params['zscore_mean']},")
    lines.append(f"  sd: {params['zscore_sd']},")
    lines.append("} as const;")
    lines.append("")

    # Sigmoid
    lines.append(f"export const OPTIMIZED_SIGMOID_STEEPNESS = {params['sigmoid_steepness']};")
    lines.append("")

    # Kelly / position sizing
    lines.append("export const OPTIMIZED_KELLY = {")
    lines.append(f"  fraction: {params['kelly_fraction']},")
    lines.append(f"  maxPositionPct: {params['max_position_pct']},")
    lines.append(f"  payoffRatio: {params['payoff_ratio']},")
    lines.append("} as const;")
    lines.append("")

    # Transaction costs
    lines.append("export const OPTIMIZED_COSTS = {")
    lines.append(f"  transactionCostBps: {params['transaction_cost_bps']},")
    lines.append(f"  slippageBps: {params['slippage_bps']},")
    lines.append("} as const;")
    lines.append("")

    # Entry thresholds
    lines.append("export const OPTIMIZED_THRESHOLDS = {")
    lines.append(f"  buyProbThreshold: {params['buy_prob_threshold']},")
    lines.append(f"  buyEdgeThreshold: {params['buy_edge_threshold']},")
    lines.append("} as const;")
    lines.append("")

    # Empirical probability map
    prob_map = params["empirical_prob_map"]
    lines.append("export const OPTIMIZED_EMPIRICAL_PROB_MAP: ReadonlyArray<[number, number]> = [")
    for threshold, prob in prob_map:
        lines.append(f"  [{threshold}, {prob}],")
    lines.append("];")
    lines.append("")

    return "\n".join(lines) + "\n"


def main():
    serializable = serialize_params(PARAMS)

    # Write JSON
    with open(JSON_OUT, "w") as f:
        json.dump(serializable, f, indent=2)
    print(f"Wrote {JSON_OUT}")

    # Write TypeScript
    ts_content = generate_typescript(PARAMS)
    with open(TS_OUT, "w") as f:
        f.write(ts_content)
    print(f"Wrote {TS_OUT}")


if __name__ == "__main__":
    main()
